# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fasthtml-dashboard-tutorial',
                'doc_host': 'https://pydanny.github.io',
                'git_url': 'https://github.com/pydanny/fasthtml-dashboard-tutorial',
                'lib_path': 'fasthtml_dashboard_tutorial'},
  'syms': { 'fasthtml_dashboard_tutorial.core': { 'fasthtml_dashboard_tutorial.core.foo': ( 'core.html#foo',
                                                                                            'fasthtml_dashboard_tutorial/core.py')}}}
